[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "midas2.0_tutorial"
authors = [{name = "Chunyu Zhao", email = "chunyu.zhao@czbiohub.org"}]
dynamic = ["version", "description"]
